### ISSUE TITLE
Login Form Validation

### ISSUE THREAD

**Issue by SwastikC28** [SwastikC28/Blog-IT-MERN-Stack-OpenCode#1]
Validate all the fields present in the Login Page i.e Email and Password.
>Password must be more than 7 characters.
>Login Button must be **disabled** until and unless all the fields are filled properly.

**Comment by Aniket-508** [comment]
@SwastikC28 Is the contribution phase started for opencode? If yes, I wanted to work on this issue.

**Comment by SwastikC28** [comment]
> @SwastikC28 Is the contribution phase started for opencode? If yes, I wanted to work on this issue.

You Can Start Contributing to this Project. Keep Contributing and Explore Other Issues after You are done with this one.
